
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listBlueprints() : Promise<Result<BpView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_blueprints") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the rich crafting view for one blueprint: named material slots, each
 * with its material, min-quality, and gameplay-property modifier curves. The
 * `/crafting` page calls this lazily when a blueprint is selected (vs.
 * `list_blueprints`, which stays lean for the catalog). `None` when the
 * blueprint has no recipe / isn't in the catalog.
 */
async getCraftDetail(blueprintGuid: string) : Promise<Result<CraftDetail | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_craft_detail", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMissions() : Promise<Result<MissionView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_missions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Map of `blueprint_record_guid → missions that grant it`, derived by
 * inverting the cooked mission list. Powers the wishlist's ⚐ fulfilment slot
 * ("which missions grant this blueprint?"). Awaits the same shared cooked
 * data as `list_missions` — no extra load cost when the catalog is warm.
 */
async missionsByBlueprint() : Promise<Result<Partial<{ [key in string]: MissionRef[] }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("missions_by_blueprint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCraftProjects() : Promise<Result<CraftProject[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_craft_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCraftProject(name: string) : Promise<Result<CraftProject, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_craft_project", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCraftProject(id: RecordId, name: string, notes: string | null) : Promise<Result<CraftProject | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_craft_project", { id, name, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCraftProject(id: RecordId) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_craft_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle whether a project counts toward the materials rollup + reservation.
 */
async setCraftProjectActive(id: RecordId, active: boolean) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_craft_project_active", { id, active }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a manual project order — `ids` in the new display order.
 */
async reorderCraftProjects(ids: RecordId[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_craft_projects", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCraftPlan() : Promise<Result<CraftPlanEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_craft_plan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCraftPlanEntry(blueprintGuid: string, projectId: RecordId | null) : Promise<Result<CraftPlanEntry, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_craft_plan_entry", { blueprintGuid, projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Overwrite a plan entry's editable fields. The UI sends the full current
 * state, so a `None` `target_quality` / `project_id` / `notes` means
 * "Base / Unsorted / no note", not "leave unchanged". `None` return ⇒ no such
 * entry in the active scope (e.g. deleted concurrently).
 */
async updateCraftPlanEntry(id: RecordId, projectId: RecordId | null, quantity: number, targetQuality: number | null, notes: string | null) : Promise<Result<CraftPlanEntry | null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_craft_plan_entry", { id, projectId, quantity, targetQuality, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a manual entry order — `ids` in the new display order (one group's
 * worth, or any subset).
 */
async reorderCraftPlan(ids: RecordId[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_craft_plan", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCraftPlanEntry(id: RecordId) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_craft_plan_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOwned() : Promise<Result<OwnedBlueprint[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_owned") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addOwned(blueprintGuid: string) : Promise<Result<OwnedBlueprint, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeOwned(blueprintGuid: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip ownership of a blueprint in the active scope. Returns the new
 * owned state (`true` = now owned). Stage 3's primary write path.
 */
async toggleOwned(blueprintGuid: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWishlist() : Promise<Result<WishlistEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_wishlist") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip one wishlist intent for a blueprint in the active scope. The two
 * intents (`Recipe` = want the BP, `Item` = want a crafted copy) toggle
 * independently. Returns the new state (`true` = now wanted).
 */
async toggleWishlist(blueprintGuid: string, intent: WishIntent) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_wishlist", { blueprintGuid, intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Surface the active platform + channel + account so the UI can show
 * "PU · LIVE · @VeeLume" or similar. Fast — needs only discovery + db,
 * not the catalog, so the sidebar renders without waiting on the DCB
 * parse.
 */
async activeScope() : Promise<Result<ActiveScope, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("active_scope") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every RSI account this desktop has known. Stage 3 wires this
 * to a picker; Stage 2.5 just exposes the data.
 */
async listAccounts() : Promise<Result<Account[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scrape `/citizens/<handle>` for the given account and write the
 * immutable anchors (`citizen_record`, `enlisted`) back to the row.
 * Refreshes `last_verified`. Returns the up-to-date `Account`.
 * 
 * No-ops with an error when Hearth is in offline mode (the master online
 * switch) — the UI hides the button, but this guards the network call regardless.
 */
async verifyAccount(accountId: RecordId) : Promise<Result<Account, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Accounts with their recorded past handles, for the Accounts UI.
 */
async listAccountsDetailed() : Promise<Result<AccountWithAliases[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts_detailed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually record a past handle for an account (rename the model didn't catch).
 */
async addAccountAlias(accountId: RecordId, handle: string) : Promise<Result<AccountWithAliases[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account_alias", { accountId, handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge one account into another (same person, two rows — e.g. a rename that
 * created a duplicate). Reassigns owned + wishlist data; `from` is absorbed.
 * Manual + explicit: the tool never auto-merges two accounts.
 */
async mergeAccounts(from: RecordId, into: RecordId) : Promise<Result<AccountWithAliases[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_accounts", { from, into }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually re-scan all session logs (live + `logbackups/`) for the active
 * account and mark owned. The "Scan now" button — same role as `live_sync_now` /
 * `inventory_sync_now`. Always notifies (success even when nothing changed, so the
 * click has visible feedback).
 */
async scanLogsNow() : Promise<Result<ScanResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_logs_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Predict which cache tier the catalog load will use, so the loading screen
 * can name the path (and warn it may be slow). Fast — just checks snapshot
 * files on disk; needs only discovery.
 */
async predictedLoadTier() : Promise<Result<LoadTier, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("predicted_load_tier") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable live blueprint sync. Enabling records consent — the UI shows
 * the one-time consent dialog before calling this with `enabled = true`.
 */
async setLiveSync(enabled: boolean) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_live_sync", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable live resource-inventory sync. Enabling records the shared
 * live-sync consent (the UI shows the one-time consent dialog before calling
 * this with `enabled = true`, same as `set_live_sync`).
 */
async setLiveInventory(enabled: boolean) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_live_inventory", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable live Game.log sensing. Takes effect within one poll interval
 * (the sensor loop checks this each tick) — no restart needed.
 */
async setSensor(enabled: boolean) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sensor", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Master online switch. Off → Hearth makes no network calls at all: profile
 * lookups are blocked (re-verify errors, rename detection falls back to manual)
 * and live game-service sync stays inert even if it's enabled.
 */
async setOnline(enabled: boolean) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_online", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark the first-launch onboarding as completed (or skipped) so it doesn't
 * show again. Re-running it from Settings doesn't clear this.
 */
async setOnboardingComplete() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_complete") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the authoritative owned-blueprint set from CIG's backend and reconcile
 * the active account's prod-scope owned set to it. Emits a success/error
 * notification regardless of caller.
 */
async liveSyncNow() : Promise<Result<LiveSyncResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("live_sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the player's live inventory from CIG's backend and replace the active
 * scope's stored snapshot with it. Emits a success/error notification
 * regardless of caller.
 */
async inventorySyncNow() : Promise<Result<InventorySyncResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inventory_sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the active scope's stored resource inventory (resources + the
 * recipe-relevant discrete items), newest snapshot. Reads the DB only — no
 * network, so it works offline and reflects the last `inventory_sync_now`.
 */
async listInventory() : Promise<Result<InventoryStack[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_inventory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Wipe the SC reference-data snapshot cache at
 * `%APPDATA%/hearth/cache/` (every channel's `catalog.cook` +
 * `extract.snap`) and restart the app so the OnceCells in AppState
 * reload from scratch.
 * 
 * Personal-state data (the `hearth.db` SQLite) is *not* touched —
 * owned blueprints, accounts, and the rest of `%APPDATA%/hearth/`
 * outside `cache/` stays put. After the restart, the next launch
 * runs the cold-path live parse (~30s on a typical install) before
 * catalog UI becomes responsive again.
 * 
 * Diverges via `AppHandle::restart()` — never returns to the caller
 * on success. The frontend should expect either an error reply or a
 * hard restart.
 */
async wipeScCache() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wipe_sc_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * An RSI account this desktop has seen. One row per distinct account
 * (multi-account on the same desktop = multiple rows). Personal-state
 * tables FK back to this via `account_id`.
 * 
 * `handle` is the current display name; `citizen_record` + `enlisted`
 * are the truly-immutable public anchors scraped from
 * `/citizens/<handle>` once the user explicitly verifies. They stay
 * `None` for the no-sign-in default flow where Hearth just trusts the
 * launcher store's nickname.
 * 
 * `account_hint` (optional) stores the launcher's `heapAccountId` /
 * in-log `accountId` value. Use ONLY as a cross-reference key when
 * parsing Game.log — never as the storage primary key. CIG has been
 * observed to rotate this value during backend migrations (Oct→Dec
 * 2024), so it's not a stable identifier.
 */
export type Account = { id: RecordId; 
/**
 * Current RSI handle, e.g. `"VeeLume"`. Mutable — user can rename
 * via a paid handle change. Don't use as a join key.
 */
handle: string; 
/**
 * UEE citizen record number from the public profile (`#1196670`).
 * Immutable, assigned at account creation. `None` until the user
 * triggers a profile-verify scrape.
 */
citizen_record: number | null; 
/**
 * Account creation date from the public profile (`"2016-01-31"`).
 * Immutable. `None` until verified.
 */
enlisted: string | null; 
/**
 * When the profile was last successfully scraped + verified.
 * `None` if never verified. Drives the "re-verify if stale" decay.
 */
last_verified: string | null; 
/**
 * Launcher / in-log numeric account id (CIG's `heapAccountId`).
 * Optional cross-reference for log parsing. Never used as a key.
 */
account_hint: number | null; created_at: string }
/**
 * An account plus its recorded past handles — the Accounts UI shape.
 */
export type AccountWithAliases = { account: Account; aliases: string[] }
export type ActiveScope = { platform: Platform; channel: string; account: Account }
export type AppError = { kind: "Storage"; message: string } | { kind: "NoInstall"; message: string } | { kind: "Identity"; message: string } | { kind: "LiveSync"; message: string } | { kind: "Inventory"; message: string } | { kind: "Internal"; message: string }
/**
 * App-global preferences surfaced to the Settings page.
 */
export type AppSettings = { 
/**
 * Whether this build was compiled with the `live-sync` feature at all.
 */
live_sync_available: boolean; 
/**
 * Runtime toggle — off by default; the user opts in.
 */
live_sync_enabled: boolean; 
/**
 * Live resource-inventory sync toggle — off by default; the user opts in.
 * Shares the live-sync consent + online master switch.
 */
live_inventory_enabled: boolean; 
/**
 * Whether the one-time ToS consent has been acknowledged.
 */
live_sync_consented: boolean; 
/**
 * Game-log tracking (startup catch-up + auto-mark BPs received during
 * play). Default off — the user opts in.
 */
sensor_enabled: boolean; 
/**
 * Whether the first-launch onboarding has been completed/skipped.
 */
onboarding_completed: boolean; 
/**
 * Master online switch (default on). Off → fully offline: no profile
 * lookups (identity / rename detection) and no live game-service sync.
 */
online_enabled: boolean }
/**
 * One blueprint-pool reward on a mission: a weighted set the contract draws
 * from, with the chance the draw happens at all.
 */
export type BpPoolReward = { 
/**
 * `BlueprintPoolRecord` name (prefix stripped). Empty if unnamed.
 */
pool_name: string; 
/**
 * 0.0–1.0 chance the blueprint draw happens.
 */
chance: number; 
/**
 * Weighted entries in the pool, descending weight.
 */
blueprints: BpRewardEntry[] }
/**
 * One weighted blueprint inside a [`BpPoolReward`].
 */
export type BpRewardEntry = { 
/**
 * `blueprint_record_guid` — matches `BpView.blueprint_record_guid` and
 * the wishlist/ownership key, so the UI can cross-reference.
 */
blueprint_record_guid: string; 
/**
 * Resolved crafted-item display name; `None` if it didn't resolve.
 */
name: string | null; 
/**
 * Relative pick-weight within the pool (higher = more likely).
 */
weight: number }
/**
 * Lean view of a craftable blueprint for the catalog UI.
 * 
 * Constructed by `sc_data::bp_view`. All GUIDs are rendered as their
 * hex-string form for the IPC boundary — the Svelte side never sees a
 * raw `Guid`.
 * 
 * The catalog source is the full `sc_crafting::Blueprints` index, not
 * the mission-reward pool registry — every craftable blueprint
 * appears, including default-unlocked ones (P4-AR, basic dismantle,
 * etc) that are in no pool. Mission-pool data (pool_guid, pool_name,
 * drop weight) is a *mission-reward* mechanic and lives in the future
 * Missions view, not here.
 */
export type BpView = { blueprint_record_guid: string; crafted_entity_guid: string | null; 
/**
 * Resolved display name. `None` when LocaleMap doesn't resolve;
 * UI should fall back to the GUID.
 */
display_name: string | null; 
/**
 * Raw CIG item-type classification of the crafted entity
 * (`AttachDef.Type`), e.g. `"Char_Armor_Helmet"`, `"WeaponPersonal"`.
 * `None` when the crafted entity didn't resolve or carried no type.
 * The UI maps these raw strings into friendly catalog categories.
 */
item_type: string | null; 
/**
 * Raw `AttachDef.SubType` (e.g. `"Rifle"`). `None` on most items.
 * Available for finer sub-grouping; not all items set it.
 */
item_sub_type: string | null; 
/**
 * sc-crafting category record name with the
 * `"BlueprintCategoryRecord."` prefix stripped — e.g. `"FPSArmours"`,
 * `"FPSWeapons"`, `"VehicleWeaponsS3"`, `"Medical"`. `None` when
 * the blueprint has no category reference. CIG-authored, more
 * accurate than the AttachDef-based taxonomy for "what kind of
 * craftable is this" — the UI uses it as the primary grouping
 * axis with item_type as the secondary axis (slot for armor,
 * size class for FPS weapons).
 */
category_raw: string | null; 
/**
 * Stable identity key used by the UI to bundle skin / paint /
 * special-edition variants of the same base item under a single
 * collapsible row. Comes from
 * [`sc_holotable::items::ItemCatalog::model_id_of`] — a
 * display-name-derived model key
 * (`"{category}:{design}:{item_type}:{item_sub_type}"`, e.g.
 * `"armor:geist armor:Char_Armor_Helmet:UNDEFINED"`) or a
 * `"solo:<guid>:..."` for gear with no other signal. Falls back to
 * the raw guid for non-gear entities (handled in the loader).
 */
family_id: string | null; 
/**
 * Display name of the model's **base** item — the canonical
 * unstyled variant identified by [`sc_holotable::items::Model::base`].
 * Shared across every BpView in a model; used by the catalog UI
 * as the bundle row header so the row reads the base item's name
 * even when only variants are blueprinted (the base item itself
 * might have no recipe). `None` when the BP has no crafted
 * entity, or when the base entity has no resolvable display name
 * — the UI then falls back to the shortest blueprinted name in
 * the bundle.
 */
family_base_name: string | null; 
/**
 * Crafting recipe — ingredients + craft time. `None` when the
 * blueprint has no recipe (rare; happens when the cost tree is a
 * dormant variant the live data doesn't populate) or when the
 * crafted item has no recoverable ingredient list.
 */
recipe: Recipe | null }
/**
 * The rich, per-slot crafting view for one blueprint — the data behind the
 * `/crafting` recipe calculator. Built from the same
 * `sc_crafting::Blueprint.tiers[0].recipe` as [`Recipe`], but instead of
 * flattening the cost tree it preserves the **named material slots**
 * (`CraftingCost_Select.name_info` → "Frame" / "Cabling" / …) and each
 * slot's **gameplay-property modifier curves** (how the chosen material's
 * quality reshapes the crafted item's stats). Fetched on demand per
 * blueprint (`get_craft_detail`), not embedded in the catalog's [`BpView`].
 */
export type CraftDetail = { 
/**
 * The blueprint this detail is for (hex GUID — matches
 * [`BpView::blueprint_record_guid`]).
 */
blueprint_record_guid: string; 
/**
 * Total craft time normalized to seconds. Same value as
 * [`Recipe::craft_time_seconds`].
 */
craft_time_seconds: number | null; 
/**
 * `CraftingGlobalParams.default_composition_quality` (500 in SC 4.8) —
 * the "Base" reference quality the UI's presets and modifier curves
 * anchor on. Global, repeated here so a single detail fetch is
 * self-contained.
 */
default_quality: number; 
/**
 * One entry per named material slot, in the recipe's declared order.
 */
slots: RecipeSlot[]; 
/**
 * The crafted item's **product stats** — its base gameplay-stat values
 * reshaped by the recipe's per-material modifiers. One entry per distinct
 * gameplay property the recipe touches; the per-slot modifier curves stay
 * on [`RecipeSlot::modifiers`] (the UI aggregates them live against the
 * quality sliders, joining by [`CraftModifier::gpp_guid`]) and this list
 * carries the [`ProductStat::base`] each aggregate is applied to. Empty
 * when the recipe drives no stats, or the crafted item's domain has no
 * base-stat sheet.
 */
product_stats: ProductStat[] }
/**
 * One gameplay property a slot's material quality reshapes, with the curve
 * to evaluate and the transform to display it. Projection of
 * `sc_crafting::GameplayPropertyModifier` joined to its
 * `CraftingGameplayPropertyDef` (display metadata).
 */
export type CraftModifier = { 
/**
 * The gameplay property's GUID hex — the join key to the recipe's
 * [`ProductStat`] rows ([`ProductStat::gpp_guid`]). Lets the UI gather
 * every slot modifier that drives a given product stat. `None` when the
 * modifier carries no property reference.
 */
gpp_guid: string | null; 
/**
 * Resolved property display name ("Recoil Smoothness", "Impact Force").
 * `None` when the property GUID doesn't resolve. Note CIG's display name
 * can differ from the record key.
 */
property_name: string | null; 
/**
 * Resolved unit-format string (a printf template like `"%.2f RPM"`).
 * `None` when empty / `@LOC_EMPTY`.
 */
unit_format: string | null; 
/**
 * How to present the evaluated factor (percent change / scale / raw).
 */
transform: ModifierTransform; 
/**
 * Quality→value bands. Usually one; evaluated by picking the band that
 * contains the quality (else the nearest), then linearly interpolating.
 */
ranges: ModifierRange[] }
/**
 * One planned craft — "make N copies of this blueprint['s item], to (at least)
 * this quality." The reservation/coverage ledger is *not* stored here; the UI
 * derives it from the plan + the live resource inventory. The same blueprint
 * may appear in several entries (e.g. once per project).
 */
export type CraftPlanEntry = { id: RecordId; 
/**
 * Owning project, or `None` for an "Unsorted" entry.
 */
project_id: RecordId | null; 
/**
 * The `BpView` record guid this plans to craft.
 */
blueprint_guid: string; 
/**
 * How many copies to make — the recipe cost is multiplied by this.
 */
quantity: number; 
/**
 * Target output quality `0..=1000`. `None` ⇒ Base (500). Materials below
 * this quality don't count toward the entry (a quality, not quantity, gate).
 */
target_quality: number | null; 
/**
 * Lexicographic manual-ordering key within the entry's group — also its
 * allocation priority (earlier entries claim materials first).
 */
sort_key: string; notes: string | null; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; created_at: string; updated_at: string }
/**
 * A named group of planned crafts (a loadout, an armour set). Pure grouping +
 * rollup; deleting one un-files its members rather than dropping them. Scoped
 * by `(account_id, platform)` like every personal-state row.
 */
export type CraftProject = { id: RecordId; name: string; notes: string | null; 
/**
 * Lexicographic manual-ordering key. Also the project's allocation
 * priority (earlier projects claim materials first).
 */
sort_key: string; 
/**
 * Whether this project counts toward the materials rollup + reservation.
 * An inactive project is "parked" — shown, but it doesn't reserve.
 */
active: boolean; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; created_at: string; updated_at: string }
/**
 * The four authored difficulty axes, each a `1..=8` level (`0` = unparsed).
 * Hidden from players; surfaced for tooltip / sort, and the payout's driver.
 */
export type DifficultyView = { mechanical_skill: number; mental_load: number; risk_of_loss: number; game_knowledge: number }
/**
 * One encounter the mission spawns — its difficulty class and waves.
 */
export type EncounterView = { 
/**
 * The encounter's mission-variable name (`"AmbushTarget"` / `"Wave"` / …).
 */
label: string; 
/**
 * Combat-class difficulty tag (`"VeryEasy"` … `"Hard"`), when uniform
 * across the encounter. `None` otherwise.
 */
difficulty: string | null; 
/**
 * Ordered waves/phases.
 */
waves: WaveView[] }
/**
 * Resolved reputation faction — stable GUID key + display name.
 */
export type FactionView = { 
/**
 * `FactionReputation` GUID hex — stable grouping/filter key.
 */
guid: string; 
/**
 * Display name (`"Ling Family Hauling"`). `None` if it didn't resolve.
 */
name: string | null }
/**
 * One ingredient in a [`Recipe`] — either a bulk resource or a discrete
 * item, discriminated by [`Ingredient::kind`].
 */
export type Ingredient = { 
/**
 * Which cost kind this ingredient is. Determines whether quantity
 * is read from `quantity_scu` (`Resource`) or `count` (`Item`), and
 * what `guid` points at.
 */
kind: IngredientKind; 
/**
 * Source GUID, hex-string form. A `ResourceType` GUID when `kind`
 * is [`IngredientKind::Resource`], an `EntityClassDefinition` GUID
 * when it's [`IngredientKind::Item`].
 */
guid: string; 
/**
 * `class_crc` of [`Self::guid`] — the CRC32C the EntityGraph backend
 * (and sc-dossier) identifies this resource/item by on the wire. Lets
 * the frontend match a recipe ingredient against the player's live
 * inventory ([`InventoryStack::crc`]) without re-hashing GUIDs. `None`
 * when the GUID doesn't parse (the name/coverage UI then falls back to
 * "untracked").
 */
crc: number | null; 
/**
 * Resolved display name (e.g. `"Aluminum"`, `"Hadanite"`). `None`
 * when the source's `name_key` doesn't resolve in the locale map.
 */
name: string | null; 
/**
 * Quantity normalized to SCU (Standard Cargo Units), for `Resource`
 * ingredients. `None` for `Item` ingredients (use `count`), or when
 * the cost's `CargoQuantity` is a polymorphic-fallback variant the
 * generator doesn't recognise. Typical resource ingredients are
 * well under 1 SCU each (e.g. P4-AR: Aluminum 0.04, Iron 0.02).
 */
quantity_scu: number | null; 
/**
 * Quantity as a discrete unit count, for `Item` ingredients (e.g.
 * Hadanite ×13). `None` for `Resource` ingredients (use
 * `quantity_scu`).
 */
count: number | null; 
/**
 * Minimum required quality tier (`0` if no lower bound).
 */
min_quality: number }
/**
 * Whether a recipe ingredient is a bulk resource or a discrete item.
 * 
 * SC recipes mix two cost kinds: `Resource` ingredients are
 * ship-mined / refined materials measured in SCU cargo
 * (`CraftingCost_Resource` → `ResourceType`); `Item` ingredients are
 * discrete carried entities measured as a unit count
 * (`CraftingCost_Item` → `EntityClassDefinition`) — the hand-mined
 * gems (Hadanite, …) live here. SC 4.8 has both in real recipes, so
 * the catalog must surface both.
 */
export type IngredientKind = 
/**
 * Bulk resource — quantity in SCU (see [`Ingredient::quantity_scu`]).
 */
"resource" | 
/**
 * Discrete item — quantity is a unit count (see [`Ingredient::count`]).
 */
"item"
/**
 * Where an inventory stack physically sits, classified from sc-dossier's
 * `Context`. `Location` / `Hangar` carry a resolved place name in
 * [`InventoryStack::location_name`]; `Container` carries the owning ship/box
 * geid in [`InventoryStack::container_geid`] (a live instance id, not
 * holotable-resolvable to a name). Storage form is the lowercase string.
 */
export type InventoryLocationKind = 
/**
 * On the character (`PlayerInventory`).
 */
"player" | 
/**
 * A world location (the `location_name` is the resolved place).
 */
"location" | 
/**
 * A hangar (the `location_name` is the resolved place).
 */
"hangar" | 
/**
 * Inside a ship/container (the `container_geid` is its instance id).
 */
"container" | 
/**
 * Bound to an entitlement.
 */
"entitlement" | 
/**
 * Any other / future context kind.
 */
"other"
/**
 * One stack in the player's live inventory, resolved from sc-dossier's wire
 * data against the catalog at sync time. Scoped by `(account_id, platform)`
 * like every personal-state row, and replaced wholesale on each authoritative
 * sync (it's a snapshot, not an incremental ledger).
 * 
 * [`Self::kind`] discriminates the two shapes — the same split recipes use:
 * a [`IngredientKind::Resource`] stack carries [`Self::scu`] + [`Self::quality`];
 * a [`IngredientKind::Item`] stack carries [`Self::count`]. [`Self::crc`] is the
 * match key — `resource_id` for resources, `class_crc` for items — so a recipe
 * ingredient ([`Ingredient::crc`]) lines up against it directly.
 */
export type InventoryStack = { id: RecordId; 
/**
 * `resource_id` (resource stacks) or `class_crc` (item stacks) — the
 * EntityGraph wire id this stack is keyed on. Matches [`Ingredient::crc`].
 */
crc: number; 
/**
 * Whether this is a bulk resource stack or a discrete item stack.
 */
kind: IngredientKind; 
/**
 * Resolved display name (e.g. `"Aluminum"`, `"Hadanite"`). `None` when the
 * CRC didn't resolve against the catalog at sync time.
 */
name: string | null; 
/**
 * Material quality `0..=1000`, for `Resource` stacks. `None` for items.
 */
quality: number | null; 
/**
 * Quantity in SCU, for `Resource` stacks. `None` for items.
 */
scu: number | null; 
/**
 * Discrete unit count, for `Item` stacks. `None` for resources.
 */
count: number | null; 
/**
 * Where this stack sits.
 */
location_kind: InventoryLocationKind; 
/**
 * Resolved place name for `Location` / `Hangar` contexts. `None` otherwise
 * or when the place CRC didn't resolve.
 */
location_name: string | null; 
/**
 * Owning ship/container geid (decimal string) for `Container` contexts.
 * `None` otherwise. String, not u64, to stay IPC/serde-friendly.
 */
container_geid: string | null; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; 
/**
 * When this snapshot was synced.
 */
synced_at: string }
/**
 * Outcome of one inventory sync, for the Settings UI + the notification body.
 */
export type InventorySyncResult = { 
/**
 * Distinct resource stacks persisted (a material at a quality in a place).
 */
resources: number; 
/**
 * Distinct item stacks persisted (recipe-relevant discrete items).
 */
items: number; 
/**
 * Total resource SCU across all resource stacks.
 */
total_scu: number }
/**
 * A non-currency item reward (ship unlock, collector item, …).
 */
export type ItemRewardView = { entity_guid: string; 
/**
 * Resolved item display name; `None` if it didn't resolve.
 */
name: string | null; amount: number }
/**
 * Outcome of one live sync, for the Settings UI + the notification body.
 */
export type LiveSyncResult = { 
/**
 * Blueprints the server reported owned.
 */
total: number; 
/**
 * Newly marked owned this sync.
 */
added: number; 
/**
 * Un-owned this sync (reconcile — the server no longer lists them).
 */
removed: number; 
/**
 * Server blueprint ids with no matching catalog entry.
 */
unresolved: number }
/**
 * Which cache tier the next catalog load will *likely* use, for the loading
 * message. Predicted from snapshot-file existence (cheap, no parse) — not a
 * guarantee: a stale snapshot after an SC patch still falls through to a
 * slower tier, which is why the UI pairs it with a "may take longer" note.
 */
export type LoadTier = 
/**
 * Processed snapshot present — sub-second.
 */
"processed" | 
/**
 * Only the raw extract snapshot present — re-parse, medium.
 */
"cache" | 
/**
 * No snapshot — live `Data.p4k` parse, slow.
 */
"raw"
/**
 * Resolved mission category — name + optional icon hints.
 */
export type MissionCategoryView = { 
/**
 * Display name (`"Hauling"`). `None` if the locale didn't resolve.
 */
name: string | null; 
/**
 * `MissionType.IconName` — UI icon id, empty string when none.
 */
icon: string }
/**
 * A reference to a mission that grants a blueprint — the lean shape the
 * wishlist's ⚐ fulfilment slot needs to answer "which missions grant this
 * BP?". Derived (not stored) by inverting the cooked [`MissionView`] list;
 * see [`crate::missions::missions_by_blueprint`]. Inverting the *pooled*
 * `MissionView`s (rather than sc-missions' raw `missions_for_item`) keeps
 * these refs consistent with the templates the Missions view renders —
 * same `mission_id`, same title.
 */
export type MissionRef = { 
/**
 * Matches [`MissionView::mission_id`] so the UI can cross-reference the
 * Missions view.
 */
mission_id: string; 
/**
 * Resolved mission title; `None` → UI falls back to the id / debug name.
 */
title: string | null; 
/**
 * Mirrors [`MissionView::once_only`]. A non-repeatable source is worth
 * flagging — the BP can only be earned from it once.
 */
once_only: boolean }
/**
 * Lean view of a mission **template** for the Missions UI.
 * 
 * Built from `sc_missions::Mission` (+ its `BlueprintPools` / `Localities`)
 * in the loader. CIG spawns one contract per offered locality, so the raw
 * list has thousands of near-duplicates; the loader **pools** contracts that
 * share a `(title_key, description_key)` into one template (the mission a
 * player perceives), aggregating the localities into [`Self::regions`].
 * Reward axes are surfaced for the blueprint focus (blueprints first), plus
 * aUEC / scrip / reputation / item unlocks. Reputation carries the raw
 * faction GUID for now.
 */
export type MissionView = { 
/**
 * Representative contract GUID, hex-string form. Stable id for UI keys.
 */
mission_id: string; 
/**
 * Resolved title; `None` → the UI falls back to `debug_name`.
 * `~mission(Var)` runtime markers are rendered as readable `[Var]`.
 */
title: string | null; 
/**
 * Internal contract debug name — fallback label + DCB cross-ref.
 */
debug_name: string; 
/**
 * Resolved description, with `~mission(Var)` → `[Var]`. Real line breaks
 * (the locale stores them as the literal two-char `\n`).
 */
description: string | null; 
/**
 * Mission category (SCMDB's "Mission Type" — Bounty Hunter / Hauling /
 * Mercenary / Salvage / …), resolved from the template's display info.
 * `None` when the mission has no category.
 */
category: MissionCategoryView | null; 
/**
 * Reputation faction (SCMDB's "Faction") — the giving / gaining faction
 * the UI groups + filters by. `None` when the mission touches no faction.
 */
faction: FactionView | null; 
/**
 * Difficulty profile (the four 1–8 axes). Players don't see this in-game;
 * it drives the computed payout. `None` when no difficulty is authored.
 */
difficulty: DifficultyView | null; 
/**
 * aUEC payout — fixed amount, evergr3n-estimate, or engine-calculated,
 * plus the buy-in and time budget. See [`PayoutView`].
 */
payout: PayoutView; 
/**
 * `availability.once_only` — non-repeatable.
 */
once_only: boolean; shareable: boolean; illegal: boolean; 
/**
 * Post-completion personal cooldown in seconds, if any.
 */
cooldown_seconds: number | null; scrip: ScripRewardView[]; reputation: RepRewardView[]; item_rewards: ItemRewardView[]; 
/**
 * Blueprint-pool rewards — each a weighted pool the contract draws from
 * (union across the pooled contracts, deduped by pool).
 */
blueprint_rewards: BpPoolReward[]; 
/**
 * Reputation a player must hold to accept (faction + standing-tier range).
 * Empty when ungated.
 */
rep_required: RepRequirementView[]; 
/**
 * Missions that must be completed first to unlock this one (the chain
 * gate), resolved from completion-tag prerequisites. Empty when ungated.
 */
chain_required: MissionRef[]; 
/**
 * Where the mission is offered — grouped by star system, each place
 * carrying its typed kind (station / planet / outpost / …). The UI's
 * system sub-split + position-type axis come from this.
 */
locations: RegionView[]; 
/**
 * Structured encounters — ships (with counts + resolved cargo) and the
 * difficulty class. Empty when the mission has no ship/entity encounter.
 */
encounters: EncounterView[]; 
/**
 * `~mission(Var)` runtime-substitution variable names present in the
 * title / description (e.g. `["Location", "CargoGradeToken"]`). The UI
 * can cross-reference them against `locations` / `encounters`.
 */
placeholders: string[]; 
/**
 * How many raw contract expansions this entry collapses (offered-at-N).
 */
instance_count: number }
/**
 * Flattened `sc_crafting::ValueRange` — one quality→value band, linearly
 * interpolated and clamped to `[start_quality, end_quality]`. `additive`
 * distinguishes a multiplicative band (`Linear`, the common case — `×factor`)
 * from an additive one (`LinearIntegerAdditive` — `+value`). Additive ints
 * are widened to `f32`.
 */
export type ModifierRange = { additive: boolean; start_quality: number; end_quality: number; at_start: number; at_end: number }
/**
 * Flattened `sc_crafting::DisplayTransformation` — how a modifier's raw
 * factor is shown. Kept as a tagged struct (not a data enum) for clean TS
 * bindings. `kind` ∈ `scale` | `factor_to_percent` |
 * `factor_to_negated_percent` | `value_to_factor` | `raw`. `raw` covers
 * the rare `Sequence` / dormant variants (show the ×factor, no percent).
 */
export type ModifierTransform = { kind: string; 
/**
 * Scalar for `kind == "scale"`; `None` otherwise.
 */
scale_factor: number | null }
/**
 * A blueprint the user has acquired in-game. Unique by
 * `(blueprint_guid, platform, account_id)` — the same BP can be
 * independently "owned" on prod and on a test shard, and across
 * multiple RSI accounts on the same desktop.
 */
export type OwnedBlueprint = { id: RecordId; 
/**
 * `Guid` from sc-extract, rendered as the hex string sc-holotable
 * uses externally. String here so the type stays serde/specta-friendly
 * without pulling sc-extract into the IPC layer.
 */
blueprint_guid: string; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; owned_at: string }
/**
 * aUEC payout, the visible reward axis the UI groups/sorts by.
 * 
 * The static DCB rarely stores a number for generated contracts — the engine
 * computes it from the difficulty profile (the community "evergr3n" formula
 * SCMDB uses). Until that estimator lands, `estimate` is `None` and the UI
 * shows "calculated". A `fixed` amount wins when the contract hardcodes one.
 */
export type PayoutView = { 
/**
 * True when the reward is engine-calculated (`ContractResult_CalculatedReward`).
 */
calculated: boolean; 
/**
 * A hardcoded fixed aUEC amount, when the contract carries one.
 */
fixed: number | null; 
/**
 * Estimated aUEC: `round₂₅₀(1232 · 1.354^weighted_difficulty · minutes)`,
 * the exponential-in-difficulty payout curve. `None` for fixed/absent
 * payouts or when difficulty inputs are missing.
 */
estimate: number | null; 
/**
 * Upfront cost to accept (`contractBuyInAmount`), 0 when free.
 */
buy_in: number; 
/**
 * Time budget in minutes (`timeToComplete`), 0 when none.
 */
time_to_complete: number }
/**
 * One accept-location — a resolved place + its typed kind.
 */
export type PlaceView = { 
/**
 * Display name (`"Bloom"`, `"microTech"`). `None` if it didn't resolve;
 * the UI falls back to [`Self::record_name`].
 */
name: string | null; 
/**
 * Stable record-name stem (`"Pyro3"`), always present.
 */
record_name: string; 
/**
 * Typed `LocationKind` as a string (`"Planet"`, `"Station"`, `"Outpost"`,
 * …) — the in-game position type. `None` when unresolved.
 */
kind: string | null }
/**
 * Which SC services environment a piece of personal state belongs to.
 * 
 * Matches CIG's launcher-store `platform_id` value verbatim: Live and
 * Hotfix run on `prod` (the persistent universe; long-lived state).
 * PTU, EPTU, and Tech Preview run on `ptu` test shards that wipe
 * regularly. Strict separation keeps test-shard progress from
 * polluting PU state.
 * 
 * Storage form is the lowercase string (`'prod'` / `'ptu'`) — same as
 * what `sc_discovery::Installation::platform_id` produces.
 */
export type Platform = 
/**
 * Production / persistent universe (Live + Hotfix).
 */
"prod" | 
/**
 * Test shards (PTU + EPTU + Tech Preview). Wipes frequently.
 */
"ptu"
/**
 * One row in the crafted item's **product-stat sheet** — its full base stats
 * (fire rate, damage, recoil, armor resistances, integrity, …), with the rows
 * the recipe reshapes carrying a link to the modifier curves so the UI can
 * show the absolute final value (`base × aggregate-factor + aggregate-additive`)
 * and the percent change. Built from the v0.14.0 per-domain base-stat sheets
 * (`FpsWeapons` / `Armor` / `ShipComponents` / `ShipWeapons`) overlaid with the
 * recipe's gameplay-property modifiers; the aggregation runs client-side so it
 * tracks the per-slot quality sliders live (`src/lib/domain/crafting.ts`).
 */
export type ProductStat = { 
/**
 * Optional section header for grouped display ("Damage Resistance",
 * "Temperature", "Radiation", …). `None` → ungrouped (a flat row).
 */
group: string | null; 
/**
 * Display label ("Fire Rate", "Recoil Pitch", "Physical Resistance").
 */
label: string; 
/**
 * Join key — the gameplay property's GUID hex the recipe modifies this
 * stat through. Matches the `gpp_guid` on each [`CraftModifier`], so the UI
 * can gather every slot modifier that drives this stat and aggregate them.
 * `None` when the recipe doesn't touch this stat (an unmodified base row,
 * shown as-is).
 */
gpp_guid: string | null; 
/**
 * Unit suffix, including any leading space (`" RPM"`, `"°"`, `"%"`, `" HP"`,
 * `" Mm/s"`). Empty when unitless. Appended straight after the value.
 */
unit: string; 
/**
 * Whether a *higher* value is better for this stat — drives the buff/nerf
 * colour. A drop in a lower-is-better stat (recoil, spread, quantum-fuel)
 * is a **buff** and should read green, not red. `None` when the direction
 * is unknown (an unmodelled property); the UI then colours by raw sign.
 */
higher_is_better: boolean | null; 
/**
 * The crafted item's base value for this stat, in display units. `None` →
 * percent-only (no absolute base in static data, e.g. tractor /
 * hull-scraping); the UI then shows just the percent change.
 */
base: number | null }
/**
 * Flat projection of a `sc_crafting::Blueprint.tiers[0].recipe` shaped
 * for the catalog UI. Today's SC 4.8 data is uniformly
 * `Select { N, [Select { 1, [Resource] }] }`, which we flatten to a
 * straight `Vec<Ingredient>`. The polymorphic cost tree stays in
 * sc-crafting as forward-compat for when CIG ships item costs /
 * optional costs / dormant variants.
 */
export type Recipe = { 
/**
 * Total craft time normalized to seconds (from
 * `TimeValue_Partitioned.{days,hours,minutes,seconds}`). `None`
 * when the blueprint has no time component.
 */
craft_time_seconds: number | null; 
/**
 * Each resource the recipe needs. Order matches the DCB's
 * declared cost order.
 */
ingredients: Ingredient[] }
/**
 * One named material slot in a [`CraftDetail`] — a material plus the
 * gameplay-property effects its quality drives.
 */
export type RecipeSlot = { 
/**
 * Resolved slot label ("Frame", "Cabling", "Power Regulator"). `None`
 * for unnamed / placeholder slots (`<= PLACEHOLDER =>` in the DCB).
 */
slot_name: string | null; 
/**
 * The material that fills this slot (resource or item) — same shape the
 * catalog uses, with `min_quality` and resolved `name`.
 */
ingredient: Ingredient; 
/**
 * Gameplay-property modifier curves attached to this slot. Empty when
 * the slot drives no stats. Evaluated client-side against the slider
 * quality (see `src/lib/domain/crafting.ts`).
 */
modifiers: CraftModifier[] }
/**
 * Stable record-level identifier. UUIDv7 so it's time-sortable and
 * generated client-side without a central authority. Wraps `Uuid` rather
 * than exposing it directly so the storage layer can swap to e.g. ULID
 * later without touching call sites.
 */
export type RecordId = string
/**
 * One locality's worth of accept-locations — the parent "available in" card
 * (e.g. *Stanton — Hurston*, *Pyro — Region A*), expandable to its places.
 */
export type RegionView = { 
/**
 * System display name (`"Stanton"`, `"Pyro"`, `"Nyx"`).
 */
system: string; 
/**
 * Locality name (`"Hurston"`, `"Region A"`) — the parent grouping a
 * mission is offered in. Empty when the locality has no name.
 */
name: string; 
/**
 * The places within this locality the mission is offered at.
 */
places: PlaceView[] }
/**
 * One reputation-acceptance requirement — a faction and the standing-tier
 * window the player must sit in.
 */
export type RepRequirementView = { 
/**
 * Faction display name. `None` if it didn't resolve.
 */
faction: string | null; 
/**
 * Lower standing-tier bound (`"Neutral"`), resolved name. `None` if unbounded.
 */
min_rank: string | null; 
/**
 * Upper standing-tier bound. `None` if unbounded.
 */
max_rank: string | null; 
/**
 * Numeric tier index of [`Self::min_rank`] (`0`–`6` on the generic
 * `FactionRep` scale), for ordering / range filters. `None` if unbounded
 * or unparsed. (Groundwork for the sc-dossier "missions I can accept"
 * filter, which will compare against the player's live standing.)
 */
min_rank_index: number | null; 
/**
 * Numeric tier index of [`Self::max_rank`]. `None` if unbounded.
 */
max_rank_index: number | null; 
/**
 * True for an *exclusion* requirement (must NOT be in this range).
 */
exclude: boolean }
/**
 * A reputation reward on a mission. Faction is a raw GUID for now (name
 * resolution is a follow-up); `amount` is `None` for engine-calculated rep.
 */
export type RepRewardView = { faction_guid: string | null; amount: number | null }
/**
 * Outcome of one log scan — the Settings echo + notification body.
 */
export type ScanResult = { 
/**
 * Blueprint records newly flipped to owned this scan.
 */
newly_owned: number; 
/**
 * Received-blueprint names that matched no catalog entry (name drift / locale).
 */
unresolved: string[] }
/**
 * A typed-currency (scrip) reward on a mission.
 */
export type ScripRewardView = { 
/**
 * Resolved currency display name; `None` if it didn't resolve.
 */
name: string | null; amount: number }
/**
 * One ship slot — how many of which candidate ships, and their factions.
 */
export type ShipSlotView = { 
/**
 * Concurrent-spawn count range across the slot's alternatives.
 */
count_min: number; count_max: number; 
/**
 * Candidate ship display names (the engine picks one per spawn).
 */
ships: string[]; 
/**
 * Faction descriptors on the slot (deduped).
 */
factions: string[] }
/**
 * One wave/phase of an encounter.
 */
export type WaveView = { 
/**
 * Wave name (`"Wave1"` / `"SalvageableShip"` / empty).
 */
name: string; 
/**
 * Ship slots in this wave.
 */
ships: ShipSlotView[]; 
/**
 * Resolved cargo descriptors across the wave's slots (deduped).
 */
cargo: string[] }
/**
 * What a wishlist entry expresses. A blueprint↔item is 1:1, but "I want
 * this" is ambiguous between wanting the recipe and wanting a crafted
 * copy — two independent goals a single BP can carry at once.
 * 
 * Storage form is the lowercase string (`'recipe'` / `'item'`).
 */
export type WishIntent = 
/**
 * Want the blueprint/recipe itself — the capability to craft it
 * (collector goal, or a prerequisite). Only meaningful while the BP
 * is *unowned* (owning it means you already have the recipe).
 * Fulfilled by mission rewards.
 */
"recipe" | 
/**
 * Want a crafted copy of the item in hand. Meaningful regardless of
 * ownership (own the BP → craft it; don't → learn it first).
 * Fulfilled by crafting (self, v1.5) or community (v2).
 */
"item"
/**
 * A blueprint↔item the user wants, carrying a single [`WishIntent`].
 * Unique by `(blueprint_guid, intent, platform, account_id)` — the two
 * intents coexist as separate rows for one BP.
 */
export type WishlistEntry = { id: RecordId; blueprint_guid: string; intent: WishIntent; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; added_at: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
