
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listBlueprints() : Promise<Result<BpView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_blueprints") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMissions() : Promise<Result<MissionView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_missions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Map of `blueprint_record_guid → missions that grant it`, derived by
 * inverting the cooked mission list. Powers the wishlist's ⚐ fulfilment slot
 * ("which missions grant this blueprint?"). Awaits the same shared cooked
 * data as `list_missions` — no extra load cost when the catalog is warm.
 */
async missionsByBlueprint() : Promise<Result<Partial<{ [key in string]: MissionRef[] }>, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("missions_by_blueprint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOwned() : Promise<Result<OwnedBlueprint[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_owned") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addOwned(blueprintGuid: string) : Promise<Result<OwnedBlueprint, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeOwned(blueprintGuid: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip ownership of a blueprint in the active scope. Returns the new
 * owned state (`true` = now owned). Stage 3's primary write path.
 */
async toggleOwned(blueprintGuid: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWishlist() : Promise<Result<WishlistEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_wishlist") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Flip one wishlist intent for a blueprint in the active scope. The two
 * intents (`Recipe` = want the BP, `Item` = want a crafted copy) toggle
 * independently. Returns the new state (`true` = now wanted).
 */
async toggleWishlist(blueprintGuid: string, intent: WishIntent) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_wishlist", { blueprintGuid, intent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Surface the active platform + channel + account so the UI can show
 * "PU · LIVE · @VeeLume" or similar. Fast — needs only discovery + db,
 * not the catalog, so the sidebar renders without waiting on the DCB
 * parse.
 */
async activeScope() : Promise<Result<ActiveScope, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("active_scope") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every RSI account this desktop has known. Stage 3 wires this
 * to a picker; Stage 2.5 just exposes the data.
 */
async listAccounts() : Promise<Result<Account[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scrape `/citizens/<handle>` for the given account and write the
 * immutable anchors (`citizen_record`, `enlisted`) back to the row.
 * Refreshes `last_verified`. Returns the up-to-date `Account`.
 */
async verifyAccount(accountId: RecordId) : Promise<Result<Account, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Accounts with their recorded past handles, for the Accounts UI.
 */
async listAccountsDetailed() : Promise<Result<AccountWithAliases[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts_detailed") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually record a past handle for an account (rename the model didn't catch).
 */
async addAccountAlias(accountId: RecordId, handle: string) : Promise<Result<AccountWithAliases[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account_alias", { accountId, handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge one account into another (same person, two rows — e.g. a rename that
 * created a duplicate). Reassigns owned + wishlist data; `from` is absorbed.
 * Manual + explicit: the tool never auto-merges two accounts.
 */
async mergeAccounts(from: RecordId, into: RecordId) : Promise<Result<AccountWithAliases[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_accounts", { from, into }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan the install's session logs (live + `logbackups/`) and surface the RSI
 * identities found, grouped by numeric `accountId` (renames fold together).
 * Caches the full scan in-state for [`apply_log_import`].
 */
async scanLogHistory() : Promise<Result<DiscoveredIdentity[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_log_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply the user's classification of the scanned identities: create / alias
 * accounts and mark their blueprints owned (prod scope). Uses the cached scan
 * from [`scan_log_history`].
 */
async applyLogImport(choices: ImportChoice[]) : Promise<Result<ImportResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_log_import", { choices }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Predict which cache tier the catalog load will use, so the loading screen
 * can name the path (and warn it may be slow). Fast — just checks snapshot
 * files on disk; needs only discovery.
 */
async predictedLoadTier() : Promise<Result<LoadTier, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("predicted_load_tier") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable/disable live blueprint sync. Enabling records consent — the UI shows
 * the one-time consent dialog before calling this with `enabled = true`.
 */
async setLiveSync(enabled: boolean) : Promise<Result<AppSettings, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_live_sync", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the authoritative owned-blueprint set from CIG's backend and reconcile
 * the active account's prod-scope owned set to it. Emits a success/error
 * notification regardless of caller.
 */
async liveSyncNow() : Promise<Result<LiveSyncResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("live_sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Wipe the SC reference-data snapshot cache at
 * `%APPDATA%/hearth/cache/` (every channel's `catalog.cook` +
 * `extract.snap`) and restart the app so the OnceCells in AppState
 * reload from scratch.
 * 
 * Personal-state data (the `hearth.db` SQLite) is *not* touched —
 * owned blueprints, accounts, and the rest of `%APPDATA%/hearth/`
 * outside `cache/` stays put. After the restart, the next launch
 * runs the cold-path live parse (~30s on a typical install) before
 * catalog UI becomes responsive again.
 * 
 * Diverges via `AppHandle::restart()` — never returns to the caller
 * on success. The frontend should expect either an error reply or a
 * hard restart.
 */
async wipeScCache() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wipe_sc_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * An RSI account this desktop has seen. One row per distinct account
 * (multi-account on the same desktop = multiple rows). Personal-state
 * tables FK back to this via `account_id`.
 * 
 * `handle` is the current display name; `citizen_record` + `enlisted`
 * are the truly-immutable public anchors scraped from
 * `/citizens/<handle>` once the user explicitly verifies. They stay
 * `None` for the no-sign-in default flow where Hearth just trusts the
 * launcher store's nickname.
 * 
 * `account_hint` (optional) stores the launcher's `heapAccountId` /
 * in-log `accountId` value. Use ONLY as a cross-reference key when
 * parsing Game.log — never as the storage primary key. CIG has been
 * observed to rotate this value during backend migrations (Oct→Dec
 * 2024), so it's not a stable identifier.
 */
export type Account = { id: RecordId; 
/**
 * Current RSI handle, e.g. `"VeeLume"`. Mutable — user can rename
 * via a paid handle change. Don't use as a join key.
 */
handle: string; 
/**
 * UEE citizen record number from the public profile (`#1196670`).
 * Immutable, assigned at account creation. `None` until the user
 * triggers a profile-verify scrape.
 */
citizen_record: number | null; 
/**
 * Account creation date from the public profile (`"2016-01-31"`).
 * Immutable. `None` until verified.
 */
enlisted: string | null; 
/**
 * When the profile was last successfully scraped + verified.
 * `None` if never verified. Drives the "re-verify if stale" decay.
 */
last_verified: string | null; 
/**
 * Launcher / in-log numeric account id (CIG's `heapAccountId`).
 * Optional cross-reference for log parsing. Never used as a key.
 */
account_hint: number | null; created_at: string }
/**
 * An account plus its recorded past handles — the Accounts UI shape.
 */
export type AccountWithAliases = { account: Account; aliases: string[] }
export type ActiveScope = { platform: Platform; channel: string; account: Account }
export type AppError = { kind: "Storage"; message: string } | { kind: "NoInstall"; message: string } | { kind: "Identity"; message: string } | { kind: "LiveSync"; message: string } | { kind: "Internal"; message: string }
/**
 * App-global preferences surfaced to the Settings page.
 */
export type AppSettings = { 
/**
 * Whether this build was compiled with the `live-sync` feature at all.
 */
live_sync_available: boolean; 
/**
 * Runtime toggle — off by default; the user opts in.
 */
live_sync_enabled: boolean; 
/**
 * Whether the one-time ToS consent has been acknowledged.
 */
live_sync_consented: boolean }
/**
 * One blueprint-pool reward on a mission: a weighted set the contract draws
 * from, with the chance the draw happens at all.
 */
export type BpPoolReward = { 
/**
 * `BlueprintPoolRecord` name (prefix stripped). Empty if unnamed.
 */
pool_name: string; 
/**
 * 0.0–1.0 chance the blueprint draw happens.
 */
chance: number; 
/**
 * Weighted entries in the pool, descending weight.
 */
blueprints: BpRewardEntry[] }
/**
 * One weighted blueprint inside a [`BpPoolReward`].
 */
export type BpRewardEntry = { 
/**
 * `blueprint_record_guid` — matches `BpView.blueprint_record_guid` and
 * the wishlist/ownership key, so the UI can cross-reference.
 */
blueprint_record_guid: string; 
/**
 * Resolved crafted-item display name; `None` if it didn't resolve.
 */
name: string | null; 
/**
 * Relative pick-weight within the pool (higher = more likely).
 */
weight: number }
/**
 * Lean view of a craftable blueprint for the catalog UI.
 * 
 * Constructed by `sc_data::bp_view`. All GUIDs are rendered as their
 * hex-string form for the IPC boundary — the Svelte side never sees a
 * raw `Guid`.
 * 
 * The catalog source is the full `sc_crafting::Blueprints` index, not
 * the mission-reward pool registry — every craftable blueprint
 * appears, including default-unlocked ones (P4-AR, basic dismantle,
 * etc) that are in no pool. Mission-pool data (pool_guid, pool_name,
 * drop weight) is a *mission-reward* mechanic and lives in the future
 * Missions view, not here.
 */
export type BpView = { blueprint_record_guid: string; crafted_entity_guid: string | null; 
/**
 * Resolved display name. `None` when LocaleMap doesn't resolve;
 * UI should fall back to the GUID.
 */
display_name: string | null; 
/**
 * Raw CIG item-type classification of the crafted entity
 * (`AttachDef.Type`), e.g. `"Char_Armor_Helmet"`, `"WeaponPersonal"`.
 * `None` when the crafted entity didn't resolve or carried no type.
 * The UI maps these raw strings into friendly catalog categories.
 */
item_type: string | null; 
/**
 * Raw `AttachDef.SubType` (e.g. `"Rifle"`). `None` on most items.
 * Available for finer sub-grouping; not all items set it.
 */
item_sub_type: string | null; 
/**
 * sc-crafting category record name with the
 * `"BlueprintCategoryRecord."` prefix stripped — e.g. `"FPSArmours"`,
 * `"FPSWeapons"`, `"VehicleWeaponsS3"`, `"Medical"`. `None` when
 * the blueprint has no category reference. CIG-authored, more
 * accurate than the AttachDef-based taxonomy for "what kind of
 * craftable is this" — the UI uses it as the primary grouping
 * axis with item_type as the secondary axis (slot for armor,
 * size class for FPS weapons).
 */
category_raw: string | null; 
/**
 * Stable identity key used by the UI to bundle skin / paint /
 * special-edition variants of the same base item under a single
 * collapsible row. Comes from
 * [`sc_holotable::items::ItemCatalog::model_id_of`] — a
 * display-name-derived model key
 * (`"{category}:{design}:{item_type}:{item_sub_type}"`, e.g.
 * `"armor:geist armor:Char_Armor_Helmet:UNDEFINED"`) or a
 * `"solo:<guid>:..."` for gear with no other signal. Falls back to
 * the raw guid for non-gear entities (handled in the loader).
 */
family_id: string | null; 
/**
 * Display name of the model's **base** item — the canonical
 * unstyled variant identified by [`sc_holotable::items::Model::base`].
 * Shared across every BpView in a model; used by the catalog UI
 * as the bundle row header so the row reads the base item's name
 * even when only variants are blueprinted (the base item itself
 * might have no recipe). `None` when the BP has no crafted
 * entity, or when the base entity has no resolvable display name
 * — the UI then falls back to the shortest blueprinted name in
 * the bundle.
 */
family_base_name: string | null; 
/**
 * Crafting recipe — ingredients + craft time. `None` when the
 * blueprint has no recipe (rare; happens when the cost tree is a
 * dormant variant the live data doesn't populate) or when the
 * crafted item has no recoverable ingredient list.
 */
recipe: Recipe | null }
/**
 * A discovered identity surfaced to the UI for classification.
 */
export type DiscoveredIdentity = { key: string; account_hint: number | null; handles: string[]; session_count: number; blueprint_count: number; 
/**
 * Best-guess existing account this maps to (handle/alias/hint match).
 */
suggested_account_id: RecordId | null; 
/**
 * That account's current handle, for display.
 */
suggested_handle: string | null }
/**
 * The UI's decision for one discovered identity.
 */
export type ImportChoice = { key: string; 
/**
 * `"existing"` (use `account_id`), `"new"` (create from the identity's
 * primary handle), or `"ignore"`.
 */
action: string; account_id: RecordId | null }
/**
 * Summary of an applied import.
 */
export type ImportResult = { accounts_touched: number; newly_owned: number; 
/**
 * Blueprint display names that matched no catalog entry (name drift).
 */
unresolved: string[] }
/**
 * One resource ingredient in a [`Recipe`].
 */
export type Ingredient = { 
/**
 * `ResourceType` GUID, hex-string form.
 */
resource_guid: string; 
/**
 * Resolved resource name (e.g. `"Aluminum"`). `None` when the
 * resource's `name_key` doesn't resolve in the locale map (rare
 * — SC 4.8 resolves 205 / 206).
 */
resource_name: string | null; 
/**
 * Quantity normalized to SCU (Standard Cargo Units). `None` when
 * the cost's `CargoQuantity` is a polymorphic-fallback variant
 * the generator doesn't recognise. Typical recipe ingredients are
 * well under 1 SCU each (e.g. P4-AR: Aluminum 0.04, Iron 0.02).
 */
quantity_scu: number | null; 
/**
 * Minimum required quality tier (`0` if no lower bound). Today
 * always 0 in SC 4.8.
 */
min_quality: number }
/**
 * A non-currency item reward (ship unlock, collector item, …).
 */
export type ItemRewardView = { entity_guid: string; 
/**
 * Resolved item display name; `None` if it didn't resolve.
 */
name: string | null; amount: number }
/**
 * Outcome of one live sync, for the Settings UI + the notification body.
 */
export type LiveSyncResult = { 
/**
 * Blueprints the server reported owned.
 */
total: number; 
/**
 * Newly marked owned this sync.
 */
added: number; 
/**
 * Un-owned this sync (reconcile — the server no longer lists them).
 */
removed: number; 
/**
 * Server blueprint ids with no matching catalog entry.
 */
unresolved: number }
/**
 * Which cache tier the next catalog load will *likely* use, for the loading
 * message. Predicted from snapshot-file existence (cheap, no parse) — not a
 * guarantee: a stale snapshot after an SC patch still falls through to a
 * slower tier, which is why the UI pairs it with a "may take longer" note.
 */
export type LoadTier = 
/**
 * Processed snapshot present — sub-second.
 */
"processed" | 
/**
 * Only the raw extract snapshot present — re-parse, medium.
 */
"cache" | 
/**
 * No snapshot — live `Data.p4k` parse, slow.
 */
"raw"
/**
 * A reference to a mission that grants a blueprint — the lean shape the
 * wishlist's ⚐ fulfilment slot needs to answer "which missions grant this
 * BP?". Derived (not stored) by inverting the cooked [`MissionView`] list;
 * see [`crate::missions::missions_by_blueprint`]. Inverting the *pooled*
 * `MissionView`s (rather than sc-missions' raw `missions_for_item`) keeps
 * these refs consistent with the templates the Missions view renders —
 * same `mission_id`, same title.
 */
export type MissionRef = { 
/**
 * Matches [`MissionView::mission_id`] so the UI can cross-reference the
 * Missions view.
 */
mission_id: string; 
/**
 * Resolved mission title; `None` → UI falls back to the id / debug name.
 */
title: string | null; 
/**
 * Mirrors [`MissionView::once_only`]. A non-repeatable source is worth
 * flagging — the BP can only be earned from it once.
 */
once_only: boolean }
/**
 * Lean view of a mission **template** for the Missions UI.
 * 
 * Built from `sc_missions::Mission` (+ its `BlueprintPools` / `Localities`)
 * in the loader. CIG spawns one contract per offered locality, so the raw
 * list has thousands of near-duplicates; the loader **pools** contracts that
 * share a `(title_key, description_key)` into one template (the mission a
 * player perceives), aggregating the localities into [`Self::regions`].
 * Reward axes are surfaced for the blueprint focus (blueprints first), plus
 * aUEC / scrip / reputation / item unlocks. Reputation carries the raw
 * faction GUID for now.
 */
export type MissionView = { 
/**
 * Representative contract GUID, hex-string form. Stable id for UI keys.
 */
mission_id: string; 
/**
 * Resolved title; `None` → the UI falls back to `debug_name`.
 * `~mission(Var)` runtime markers are rendered as readable `[Var]`.
 */
title: string | null; 
/**
 * Internal contract debug name — fallback label + DCB cross-ref.
 */
debug_name: string; 
/**
 * Resolved description, with `~mission(Var)` → `[Var]`. Real line breaks
 * (the locale stores them as the literal two-char `\n`).
 */
description: string | null; 
/**
 * `availability.once_only` — non-repeatable.
 */
once_only: boolean; shareable: boolean; illegal: boolean; 
/**
 * Post-completion personal cooldown in seconds, if any.
 */
cooldown_seconds: number | null; 
/**
 * Fixed aUEC payout, when the contract pays a fixed amount.
 */
uec_fixed: number | null; 
/**
 * True when the aUEC payout is engine-computed at runtime (amount unknown).
 */
uec_calculated: boolean; scrip: ScripRewardView[]; reputation: RepRewardView[]; item_rewards: ItemRewardView[]; 
/**
 * Blueprint-pool rewards — each a weighted pool the contract draws from
 * (union across the pooled contracts, deduped by pool).
 */
blueprint_rewards: BpPoolReward[]; 
/**
 * Distinct region labels (`"Pyro: Bloom"`) across the pooled contracts'
 * localities — where the mission is offered.
 */
regions: string[]; 
/**
 * One-line encounter banner (`"2-4 ships · VeryEasy"`), or `None` when
 * the mission has no ship/entity encounters.
 */
encounter_summary: string | null; 
/**
 * How many spawned contracts this template pools (offered-at-N count).
 */
instance_count: number }
/**
 * A blueprint the user has acquired in-game. Unique by
 * `(blueprint_guid, platform, account_id)` — the same BP can be
 * independently "owned" on prod and on a test shard, and across
 * multiple RSI accounts on the same desktop.
 */
export type OwnedBlueprint = { id: RecordId; 
/**
 * `Guid` from sc-extract, rendered as the hex string sc-holotable
 * uses externally. String here so the type stays serde/specta-friendly
 * without pulling sc-extract into the IPC layer.
 */
blueprint_guid: string; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; owned_at: string }
/**
 * Which SC services environment a piece of personal state belongs to.
 * 
 * Matches CIG's launcher-store `platform_id` value verbatim: Live and
 * Hotfix run on `prod` (the persistent universe; long-lived state).
 * PTU, EPTU, and Tech Preview run on `ptu` test shards that wipe
 * regularly. Strict separation keeps test-shard progress from
 * polluting PU state.
 * 
 * Storage form is the lowercase string (`'prod'` / `'ptu'`) — same as
 * what `sc_discovery::Installation::platform_id` produces.
 */
export type Platform = 
/**
 * Production / persistent universe (Live + Hotfix).
 */
"prod" | 
/**
 * Test shards (PTU + EPTU + Tech Preview). Wipes frequently.
 */
"ptu"
/**
 * Flat projection of a `sc_crafting::Blueprint.tiers[0].recipe` shaped
 * for the catalog UI. Today's SC 4.8 data is uniformly
 * `Select { N, [Select { 1, [Resource] }] }`, which we flatten to a
 * straight `Vec<Ingredient>`. The polymorphic cost tree stays in
 * sc-crafting as forward-compat for when CIG ships item costs /
 * optional costs / dormant variants.
 */
export type Recipe = { 
/**
 * Total craft time normalized to seconds (from
 * `TimeValue_Partitioned.{days,hours,minutes,seconds}`). `None`
 * when the blueprint has no time component.
 */
craft_time_seconds: number | null; 
/**
 * Each resource the recipe needs. Order matches the DCB's
 * declared cost order.
 */
ingredients: Ingredient[] }
/**
 * Stable record-level identifier. UUIDv7 so it's time-sortable and
 * generated client-side without a central authority. Wraps `Uuid` rather
 * than exposing it directly so the storage layer can swap to e.g. ULID
 * later without touching call sites.
 */
export type RecordId = string
/**
 * A reputation reward on a mission. Faction is a raw GUID for now (name
 * resolution is a follow-up); `amount` is `None` for engine-calculated rep.
 */
export type RepRewardView = { faction_guid: string | null; amount: number | null }
/**
 * A typed-currency (scrip) reward on a mission.
 */
export type ScripRewardView = { 
/**
 * Resolved currency display name; `None` if it didn't resolve.
 */
name: string | null; amount: number }
/**
 * What a wishlist entry expresses. A blueprint↔item is 1:1, but "I want
 * this" is ambiguous between wanting the recipe and wanting a crafted
 * copy — two independent goals a single BP can carry at once.
 * 
 * Storage form is the lowercase string (`'recipe'` / `'item'`).
 */
export type WishIntent = 
/**
 * Want the blueprint/recipe itself — the capability to craft it
 * (collector goal, or a prerequisite). Only meaningful while the BP
 * is *unowned* (owning it means you already have the recipe).
 * Fulfilled by mission rewards.
 */
"recipe" | 
/**
 * Want a crafted copy of the item in hand. Meaningful regardless of
 * ownership (own the BP → craft it; don't → learn it first).
 * Fulfilled by crafting (self, v1.5) or community (v2).
 */
"item"
/**
 * A blueprint↔item the user wants, carrying a single [`WishIntent`].
 * Unique by `(blueprint_guid, intent, platform, account_id)` — the two
 * intents coexist as separate rows for one BP.
 */
export type WishlistEntry = { id: RecordId; blueprint_guid: string; intent: WishIntent; platform: Platform; 
/**
 * FK to `accounts.id`.
 */
account_id: RecordId; added_at: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
