
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listBlueprints() : Promise<Result<BpView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_blueprints") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOwned() : Promise<Result<OwnedBlueprint[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_owned") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addOwned(blueprintGuid: string) : Promise<Result<OwnedBlueprint, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeOwned(blueprintGuid: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_owned", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWishlist() : Promise<Result<WishlistEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_wishlist") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addToWishlist(blueprintGuid: string) : Promise<Result<WishlistEntry, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_to_wishlist", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFromWishlist(blueprintGuid: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_from_wishlist", { blueprintGuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { kind: "Storage"; message: string } | { kind: "NoInstall"; message: string } | { kind: "Internal"; message: string }
/**
 * Lean view of a sc-contracts `BlueprintItem` for the catalog UI.
 * 
 * Constructed by `sc_data::bp_view`. All GUIDs are rendered as their
 * hex-string form for the IPC boundary — the Svelte side never sees a
 * raw `Guid`.
 */
export type BpView = { pool_guid: string; pool_name: string; blueprint_record_guid: string; crafted_entity_guid: string | null; 
/**
 * Resolved display name. `None` until Stage 2 wires LocaleMap-driven
 * name resolution; UI should fall back to the GUID for now.
 */
display_name: string | null; weight: number }
/**
 * A blueprint the user has acquired in-game. Unique by `blueprint_guid`
 * (you can't own the same BP twice).
 */
export type OwnedBlueprint = { id: RecordId; 
/**
 * `Guid` from sc-extract, rendered as the hex string `sc-contracts`
 * uses externally. String here so the type stays serde/specta-friendly
 * without pulling sc-extract into the IPC layer.
 */
blueprint_guid: string; owned_at: string }
/**
 * Stable record-level identifier. UUIDv7 so it's time-sortable and
 * generated client-side without a central authority. Wraps `Uuid` rather
 * than exposing it directly so the storage layer can swap to e.g. ULID
 * later without touching call sites.
 */
export type RecordId = string
/**
 * A blueprint the user wants. Surfaces in lists / craft suggestions.
 */
export type WishlistEntry = { id: RecordId; blueprint_guid: string; added_at: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
