// The single Tauri IPC boundary for the frontend.
//
// `bindings.ts` is generated by tauri-specta and rewritten at this exact path
// on every debug build (see src-tauri/src/lib.rs) — never move or hand-edit it.
// Everything else in the app imports from THIS module instead of reaching into
// `bindings` or `@tauri-apps/api/event` directly, so the whole IPC surface —
// the typed `commands`, `AppError` formatting, and event subscriptions — lives
// in one place.

import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { AppError } from "$lib/bindings";

// The generated typed `commands` plus every IPC type, re-exported as the
// canonical surface callers depend on.
export * from "$lib/bindings";
export { listen, type UnlistenFn };

/** Render an `AppError` as the `"Kind: message"` string the UI shows. The one
 *  place this formatting lives — call sites used to inline it everywhere. */
export function errText(e: AppError): string {
  return `${e.kind}: ${e.message}`;
}

/** Backend event names. These string literals must match the Rust `emit`
 *  calls; keeping them here stops them drifting across the UI. */
export const EVENTS = {
  /** A backend notification (notify.rs) → the notification store. */
  notify: "notify",
  /** The owned set changed behind the UI's back (live sync, sensor auto-mark). */
  ownershipChanged: "ownership-changed",
  /** The resource inventory changed behind the UI's back (live inventory sync). */
  inventoryChanged: "inventory-changed",
  /** The active scope changed (e.g. an auto-applied handle rename). */
  activeScopeChanged: "active-scope-changed",
} as const;

/** Subscribe to `ownership-changed`; resolves to the unlisten handle. */
export function onOwnershipChanged(cb: () => void): Promise<UnlistenFn> {
  return listen(EVENTS.ownershipChanged, () => cb());
}

/** Subscribe to `inventory-changed`; resolves to the unlisten handle. */
export function onInventoryChanged(cb: () => void): Promise<UnlistenFn> {
  return listen(EVENTS.inventoryChanged, () => cb());
}

/** Subscribe to `active-scope-changed`; resolves to the unlisten handle. */
export function onActiveScopeChanged(cb: () => void): Promise<UnlistenFn> {
  return listen(EVENTS.activeScopeChanged, () => cb());
}
